// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package db

import (
	"database/sql"
	"time"
)

type Quiz struct {
	ID         interface{}   `json:"id"`
	UserID     int64         `json:"user_id"`
	Title      string        `json:"title"`
	QuestionNo int32         `json:"question_no"`
	StartAt    time.Time     `json:"start_at"`
	EndAt      sql.NullTime  `json:"end_at"`
	Questions  []interface{} `json:"questions"`
}

type Result struct {
	ID        interface{} `json:"id"`
	QuizID    int64       `json:"quiz_id"`
	Score     int32       `json:"score"`
	Responses [][]int32   `json:"responses"`
}

type User struct {
	ID        int64     `json:"id"`
	Name      string    `json:"name"`
	Email     string    `json:"email"`
	CreatedAt time.Time `json:"created_at"`
}
