services:
  db:
    container_name: quizzer-db
    image: registry.docker.ir/postgres:12-alpine
    restart: always
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: quizzer
      POSTGRES_USER: root
      POSTGRES_PASSWORD: secret
  migrate:
    container_name: quizzer-migrate
    image: migrate/migrate
    volumes:
        - ./internal/database/migration:/migrations
    command: ["-path", "/migrations", "-database",  "postgresql://root:secret@quizzer-db:5432/quizzer?sslmode=disable", "up"]
    depends_on:
      - db
  api:
    container_name: quizzer-api
    image: quizzer/api
    volumes:
      - /etc/quizzer/api:/etc/quizzer/api
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - db

volumes:
  db:

networks:
  nginx-proxy:
    external: true
